/**
 * E2E Test: Gemini → Ticket Breakdown → JIRA Creation
 * 
 * This script tests the full flow:
 * 1. Send a real request to Gemini API
 * 2. Parse the breakdown response
 * 3. Create actual tickets in JIRA (KWA project)
 * 
 * Run: npx tsx tests/e2e-jira-flow.ts
 */
import 'dotenv/config';
import { GeminiClient } from '../src/shared/clients/gemini-client.js';
import { JiraClient } from '../src/shared/clients/jira-client.js';
import { generateTicketBreakdown } from '../src/plugins/jira-automation/ticket-generator.js';

async function runE2ETest() {
  console.log('🚀 E2E Test: JIRA Auto-Breakdown Flow\n');
  console.log('='.repeat(60));

  // 1. Initialize clients
  const gemini = new GeminiClient({
    apiKey: process.env.GEMINI_API_KEY!,
    model: process.env.GEMINI_MODEL ?? 'gemini-2.5-flash',
  });

  const jira = new JiraClient({
    domain: process.env.ATLASSIAN_DOMAIN!,
    email: process.env.ATLASSIAN_EMAIL!,
    apiToken: process.env.ATLASSIAN_API_TOKEN!,
  });

  const projectKey = process.env.JIRA_PROJECT_KEY!;

  // 2. Test request (realistic Japanese business request)
  const testRequest = `
認証画面でログインボタンを押しても反応しないという問い合わせが来ています。
また、パスワードリセット機能も動作していないようです。
優先的に対応をお願いします。
  `.trim();

  console.log('\n📝 Test Request:');
  console.log('-'.repeat(60));
  console.log(testRequest);
  console.log('-'.repeat(60));

  // 3. Generate ticket breakdown via Gemini
  console.log('\n⏳ Calling Gemini API for ticket breakdown...');
  
  let breakdown;
  try {
    breakdown = await generateTicketBreakdown(gemini, testRequest);
  } catch (error) {
    console.error('❌ Gemini API Error:', error);
    console.log('\n💡 Tip: If quota exceeded, wait a few seconds and retry.');
    process.exit(1);
  }

  console.log('\n✅ Gemini Response Received!');
  console.log(`   Analysis: ${breakdown.analysisNotes}`);
  console.log(`   Parent Ticket: ${breakdown.parentTicket ? 'Yes' : 'No'}`);
  console.log(`   Sub-tickets: ${breakdown.tickets.length}`);
  console.log(`   Total Hours: ${breakdown.totalEstimatedHours}h`);

  // 4. Display breakdown details
  console.log('\n📋 Generated Tickets:');
  console.log('-'.repeat(60));

  if (breakdown.parentTicket) {
    const p = breakdown.parentTicket;
    console.log(`\n[PARENT] ${p.issueType}`);
    console.log(`  Summary: ${p.summary}`);
    console.log(`  Priority: ${p.priority}`);
    console.log(`  Confidence: ${p.confidenceScore}%`);
  }

  breakdown.tickets.forEach((ticket, i) => {
    console.log(`\n[${i + 1}] ${ticket.issueType}`);
    console.log(`  Summary: ${ticket.summary}`);
    console.log(`  Priority: ${ticket.priority}`);
    console.log(`  Hours: ${ticket.estimatedHours}h`);
    console.log(`  Confidence: ${ticket.confidenceScore}%`);
    console.log(`  Labels: ${ticket.labels.join(', ') || 'none'}`);
  });

  // 5. Create tickets in JIRA (optional - controlled by env var)
  const shouldCreateTickets = process.env.E2E_CREATE_TICKETS === 'true';
  
  if (!shouldCreateTickets) {
    console.log('\n' + '='.repeat(60));
    console.log('ℹ️  Dry run mode - tickets NOT created in JIRA');
    console.log('   Set E2E_CREATE_TICKETS=true to actually create tickets');
    console.log('='.repeat(60));
    console.log('\n✅ E2E Test Completed (dry run)');
    return;
  }

  console.log('\n' + '='.repeat(60));
  console.log('📤 Creating tickets in JIRA...');
  console.log('='.repeat(60));

  const createdTickets: Array<{ key: string; summary: string; url: string }> = [];

  for (const ticket of breakdown.tickets) {
    try {
      const issueType = ticket.issueType === 'Sub-task' ? 'Task' : ticket.issueType;
      
      const created = await jira.createIssue({
        projectKey,
        issueType: issueType as 'Bug' | 'Task' | 'Story' | 'Epic',
        summary: ticket.summary,
        description: `${ticket.description}\n\n---\n*Auto-generated by Project-K*\n*Confidence: ${ticket.confidenceScore}%*`,
        priority: ticket.priority,
        labels: ticket.labels,
      });

      const ticketUrl = `https://${process.env.ATLASSIAN_DOMAIN}.atlassian.net/browse/${created.key}`;
      createdTickets.push({
        key: created.key,
        summary: ticket.summary,
        url: ticketUrl,
      });

      console.log(`  ✅ Created: ${created.key} - ${ticket.summary}`);
    } catch (error) {
      console.error(`  ❌ Failed to create: ${ticket.summary}`);
      console.error(`     Error: ${error}`);
    }
  }

  // 6. Summary
  console.log('\n' + '='.repeat(60));
  console.log('📊 E2E Test Results');
  console.log('='.repeat(60));
  console.log(`Created ${createdTickets.length}/${breakdown.tickets.length} tickets\n`);

  createdTickets.forEach((t) => {
    console.log(`  🎫 ${t.key}: ${t.summary}`);
    console.log(`     ${t.url}`);
  });

  console.log('\n✅ E2E Test Completed!');
}

runE2ETest().catch(console.error);
